[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
ICOW = "3f0c05cb-d2a1-4c03-b976-c0e1c11e0dd4"
Metaheuristics = "bcdb8e00-2c21-11e9-3065-2b553b22f898"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimOptDecisions = "8764eb7a-9599-4112-a7c7-9b4115e89f97"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
